### ISSUE TITLE
if i want to pick color, circle duplicated

### ISSUE THREAD

**Issue by sgnd** [RonnyDo/ColorPicker#44] opened 2018-06-03 06:26 UTC
I don't know what is this error called. You can see error in this gif. 
![screencast from 2018-06-03 13 12 59](https://user-images.githubusercontent.com/15070585/40883867-1b3b8362-6731-11e8-8127-463e27512690.gif)

And this is my computer specification
![screenshot from 2018-06-03 13-23-16](https://user-images.githubusercontent.com/15070585/40883878-6b508e56-6731-11e8-9b21-795e2a7f13c5.png)

**Comment by RonnyDo** [comment] 2018-06-18 22:32
Thanks for your request, this is probably a duplicate of #29 as you have a Radeon graphic as well. So far we haven't a fix yet :-(

**Closed** 2018-06-18 22:32 UTC
